#ifndef KEYBOARDS_NRF52_SEPARATE_TEST_
#define KEYBOARDS_NRF52_SEPARATE_TEST_

#include "custom_board.h"

#define THIS_DEVICE_ROWS 4
#define THIS_DEVICE_COLS 6

#define MATRIX_ROW_PINS { ROW_PIN_0, ROW_PIN_1, ROW_PIN_2, ROW_PIN_3 }
#define MATRIX_COL_PINS { COL_PIN_5, COL_PIN_4, COL_PIN_3, COL_PIN_2, COL_PIN_1, COL_PIN_0 }
#define IS_LEFT_HAND  false

#endif /* KEYBOARDS_NRF52_SEPARATE_TEST_ */
